apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test127
  namespace: test127
spec:
  project: default
  source:
    repoURL: 'https://github.com/PekoyamaPeko02/test127.git'
    targetRevision: HEAD
    path: 'deploy.yaml'  # Update this to the correct path
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test127
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
